import { useState, useEffect } from 'react';
import { Search, ChevronRight, Activity, AlertTriangle, ShieldCheck, Database, Network as NetworkIcon, Server, Cpu, Navigation, Sparkles, FileText, LayoutList, FileOutput, ShieldAlert, CheckCircle, Loader2, Eye, Download } from 'lucide-react';
import { cn } from '../../lib/utils';
import Plot from 'react-plotly.js';
import { toCanvas } from 'html-to-image';
import { jsPDF } from 'jspdf';

// Fallback empty story state
const FALLBACK_STORY = {
  id: '--',
  title: 'Aucune donnée',
  risk: 'N/A',
  date: '--',
  sparkline: [0],
  color: '#ccc',
  narrative: 'Aucune donnée d\'investigation trouvée. Veuillez uploader un fichier de log.',
  recommendation: 'Aucune',
  timeline: [],
  playbook: []
};

// Helper to map an action to a Lucide icon
const getIconForAction = (action: string) => {
  const lower = action.toLowerCase();
  if (lower.includes('ssh') || lower.includes('auth')) return Activity;
  if (lower.includes('dns') || lower.includes('network')) return NetworkIcon;
  if (lower.includes('sql') || lower.includes('db')) return Database;
  if (lower.includes('ddos') || lower.includes('flood')) return AlertTriangle;
  if (lower.includes('smb')) return Server;
  return ShieldCheck;
};

export default function Reports() {
  const [allStorylines, setStorylines] = useState<any[]>([]);
  const [integrityData, setIntegrityData] = useState<any>(null);
  const [activeStory, setActiveStory] = useState<any>(FALLBACK_STORY);
  const [viewMode, setViewMode] = useState<'feed' | 'full' | 'archives'>('feed');
  const [archivesList, setArchivesList] = useState<any[]>([]);
  const [selectedArchiveUrl, setSelectedArchiveUrl] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Fetch the JSON generated by the python backend
    const fetchReportData = async () => {
      try {
        const [res, archivesRes] = await Promise.all([
          fetch('/api/reports/data'),
          fetch('/api/archives')
        ]);
        
        if (archivesRes.ok) {
          const archives = await archivesRes.json();
          setArchivesList(archives);
        }

        if (res.ok) {
          const rawData = await res.json();
          // Backward compatibility check if the JSON is an array (old) or the new wrapped object
          const data = Array.isArray(rawData) ? rawData : rawData.storylines;
          const integrity = rawData.integrity || null;
          
          if (data && data.length > 0) {
            // Map the icons back since JSON doesn't contain React components
            const enrichedData = data.map((story: any) => ({
              ...story,
              timeline: story.timeline.map((node: any) => ({
                ...node,
                icon: getIconForAction(node.action || story.title)
              }))
            }));
            
            setStorylines(enrichedData);
            setActiveStory(enrichedData[0]);
            
            // We expect the backend to pass the latest generated PDF path in the object
            // If it doesn't, we can fall back to the first one in the archives list.
            const latestUrl = rawData.latestPdfUrl || (archivesList.length > 0 ? archivesList[0].url : null);
            setIntegrityData({ ...integrity, latestPdfUrl: latestUrl });
          } else {
            setStorylines([]);
            setActiveStory(FALLBACK_STORY);
            setIntegrityData(null);
          }
        }
      } catch (err) {
        console.error("Failed to load report data", err);
      } finally {
        setLoading(false);
      }
    };
    
    fetchReportData();
  }, []);

  const handleDownloadPDF = () => {
    const url = viewMode === 'archives' && selectedArchiveUrl 
      ? selectedArchiveUrl 
      : integrityData?.latestPdfUrl;
      
    if (url) {
      window.open(url, '_blank');
    } else {
      alert("Erreur: Le fichier PDF n'est pas encore disponible ou généré.");
    }
  };

  if (loading) {
    return (
      <div className="flex flex-col h-full bg-slate-50 items-center justify-center">
        <Loader2 className="w-12 h-12 text-blue-500 animate-spin mb-4" />
        <p className="text-slate-600 font-bold">Extraction des données Forensic IA...</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-[calc(100vh-100px)] relative font-sans">
      
     

      {/* Header */}
      <div className="mb-6 flex flex-col md:flex-row justify-between items-start md:items-center shrink-0 gap-4">
        <div>
          <h1 className="text-3xl font-black tracking-tight" style={{ color: '#04243C' }}>Rapport Forensic Consolidé</h1>
          <p className="text-sm font-medium mt-1 text-slate-500">
            SOTETEL AI Forensic &bull; {allStorylines.length} Scénarios Analysés
          </p>
        </div>
        
        {/* Toggle View */}
        <div className="bg-slate-100 p-1 rounded-xl flex shadow-inner">
          <button 
            onClick={() => setViewMode('feed')}
            className={cn("flex justify-center items-center px-4 py-2 rounded-lg text-sm font-bold transition-all", viewMode === 'feed' ? "bg-white shadow-sm text-slate-900" : "text-slate-500 hover:text-slate-700")}
          >
            <LayoutList className="w-4 h-4 mr-2" /> Vue Rapide
          </button>
          <button 
            onClick={() => setViewMode('full')}
            className={cn("flex justify-center items-center px-4 py-2 rounded-lg text-sm font-bold transition-all", viewMode === 'full' ? "bg-[#04243C] shadow-sm text-white" : "text-slate-500 hover:text-slate-700")}
          >
            <FileText className="w-4 h-4 mr-2" /> Rapport Complet PDF
          </button>
          <button 
            onClick={() => setViewMode('archives')}
            className={cn("flex justify-center items-center px-4 py-2 rounded-lg text-sm font-bold transition-all", viewMode === 'archives' ? "bg-orange-500 shadow-sm text-white" : "text-slate-500 hover:text-slate-700")}
          >
            <Database className="w-4 h-4 mr-2" /> Historique
          </button>
        </div>
      </div>

      {/* CONDITIONAL RENDERING BASED ON VIEW MODE */}
      {viewMode === 'feed' && (
        
        /* --------------------------------------------------- */
        /* SPLIT VIEW: MASTER-DETAIL                           */
        /* --------------------------------------------------- */
        <div className="grid grid-cols-12 gap-6 flex-1 min-h-0 overflow-hidden pb-4">
          
          {/* LEFT PANEL: The Feed */}
          <div className="col-span-12 lg:col-span-3 flex flex-col gap-4 overflow-y-auto pr-2 custom-scrollbar">
            {allStorylines.map((story) => (
              <button
                key={story.id}
                onClick={() => setActiveStory(story)}
                className={cn(
                  "w-full text-left bg-white/90 backdrop-blur-md rounded-2xl p-5 transition-all duration-300 relative overflow-hidden group",
                  activeStory.id === story.id
                    ? "shadow-[0_8px_30px_rgb(0,0,0,0.08)] border-transparent"
                    : "shadow-sm border border-slate-100 hover:shadow-md hover:border-slate-200"
                )}
              >
                <div className={cn("absolute left-0 top-0 bottom-0 w-1.5 transition-all duration-300", activeStory.id === story.id ? "opacity-100" : "opacity-0")} style={{ backgroundColor: story.color }} />
                
                <div className="flex justify-between items-start mb-3">
                  <span className="text-xs font-black uppercase tracking-wider" style={{ color: '#04243C' }}>{story.id}</span>
                  <span className="text-[10px] font-bold uppercase tracking-widest px-2 py-0.5 rounded-full" style={{ color: story.color, backgroundColor: `${story.color}15` }}>
                    {story.risk}
                  </span>
                </div>
                
                <h3 className="text-sm font-bold text-slate-800 mb-1 line-clamp-1">{story.title}</h3>
                <div className="text-xs text-slate-400 mb-4 font-medium">{story.date}</div>

                {/* Sparkline Plotly */}
                <div className="h-8 w-full relative">
                  <Plot
                    data={[{ y: story.sparkline, type: 'scatter', mode: 'lines', line: { color: story.color, width: 2, shape: 'spline' } }]}
                    layout={{ margin: { t: 0, r: 0, l: 0, b: 0 }, showlegend: false, xaxis: { visible: false }, yaxis: { visible: false }, paper_bgcolor: 'transparent', plot_bgcolor: 'transparent' }}
                    config={{ displayModeBar: false, staticPlot: true }}
                    style={{ width: '100%', height: '100%', position: 'absolute' }}
                  />
                </div>
              </button>
            ))}
          </div>

          {/* CENTER PANEL: The Storyline Timeline */}
          <div className="col-span-12 lg:col-span-5 bg-white/90 backdrop-blur-md shadow-[0_8px_30px_rgb(0,0,0,0.04)] rounded-3xl border border-slate-50 flex flex-col overflow-hidden">
            <div className="p-6 border-b border-slate-100 shrink-0 bg-white/50">
              <div className="flex items-center gap-2 mb-1">
                <Sparkles className="w-4 h-4 text-orange-500" />
                <span className="text-[10px] font-black uppercase tracking-widest text-orange-500">IA Reconstructed Graph</span>
              </div>
              <h2 className="text-xl font-black tracking-tight text-slate-900">{activeStory.title}</h2>
            </div>
            
            <div className="flex-1 overflow-y-auto p-8 relative">
              <div className="absolute left-[51px] top-8 bottom-8 w-px bg-slate-200" />
              <div className="space-y-10 relative">
                {activeStory.timeline.map((node, i) => (
                  <div key={i} className="flex gap-6 relative group">
                     {/* Draw curve line to previous node if not first */}
                     {i > 0 && (
                        <svg className="absolute -top-[35px] left-5 w-16 h-12 pointer-events-none" style={{ zIndex: 0 }} fill="none">
                          <path d="M0,0 Q18,45 40,45" stroke={node.c} strokeWidth="1.5" strokeDasharray="3 3" />
                        </svg>
                     )}
                    <div className="w-10 h-10 rounded-full bg-white border-2 flex items-center justify-center shrink-0 z-10 transition-transform group-hover:scale-110 shadow-sm" style={{ borderColor: node.c, color: node.c }}>
                      <node.icon className="w-4 h-4" />
                    </div>
                    <div>
                      <div className="text-[10px] font-bold text-slate-400 mb-1">{node.time} &bull; {node.phase}</div>
                      <div className={cn("border rounded-xl p-4 shadow-sm w-full transition-colors relative overflow-hidden", node.alert ? "bg-red-50 border-red-200" : "bg-slate-50 border-slate-200")}>
                        {node.alert && <div className="absolute top-0 left-0 w-1 h-full" style={{ backgroundColor: node.c }} />}
                        <div className={cn("font-bold text-sm mb-1", node.alert ? "text-red-900" : "text-slate-800")}>{node.action}</div>
                        <div className={cn("text-xs font-medium", node.alert ? "text-red-600" : "text-slate-500")}>
                          {node.details} {node.alert && <span className="font-black ml-1">#DETECTED</span>}
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* RIGHT PANEL: The Summary */}
          <div className="col-span-12 lg:col-span-4 flex flex-col gap-6 overflow-y-auto pb-24"> {/* Added pb-24 so FAB button doesn't block */}
            <div className="bg-[#04243C] rounded-3xl p-6 shadow-xl text-white flex-shrink-0 relative overflow-hidden">
               <div className="absolute -right-10 -top-10 w-40 h-40 bg-white opacity-5 rounded-full blur-2xl" />
               <div className="flex items-center gap-3 mb-4">
                  <div className="w-8 h-8 rounded bg-white/10 flex items-center justify-center"><FileText className="w-4 h-4 text-white" /></div>
                  <h3 className="text-lg font-black tracking-wide uppercase">Executive Narrative</h3>
               </div>
               <p className="text-sm font-medium text-slate-300 leading-relaxed mb-4 relative z-10">{activeStory.narrative}</p>
               <div className="bg-black/20 rounded-xl p-4 border border-white/5 relative z-10">
                  <div className="text-[10px] text-slate-400 font-bold uppercase tracking-widest mb-1">Recommandation Immédiate</div>
                  <div className="text-sm font-bold text-orange-400">{activeStory.recommendation}</div>
               </div>
            </div>

            <div className="bg-white/90 backdrop-blur-md rounded-3xl p-6 shadow-sm border border-slate-200 flex-1 flex flex-col">
               <div className="flex items-center gap-2 mb-4 shrink-0">
                 <ShieldAlert className="w-4 h-4 text-slate-400" />
                 <h3 className="text-sm font-black tracking-tight uppercase text-slate-600">Action Playbook</h3>
               </div>
               <ul className="space-y-3 mt-2 flex-1">
                 {activeStory.playbook.map((task, i) => (
                    <li key={i} className="flex items-start text-sm">
                      <div className="w-5 h-5 rounded-full bg-slate-100 flex items-center justify-center shrink-0 mr-3 text-orange-500 font-bold text-xs mt-0.5">{i+1}</div>
                      <span className="text-slate-700 font-medium">{task}</span>
                    </li>
                 ))}
               </ul>
            </div>
          </div>
        </div>

      )}
      
      {viewMode === 'full' && (
        <div className="flex-1 w-full bg-slate-200 p-6 flex justify-center overflow-hidden">
          {integrityData?.latestPdfUrl ? (
            <iframe 
              src={integrityData.latestPdfUrl} 
              className="w-full max-w-5xl h-full rounded-xl shadow-2xl border border-slate-300"
              title="PDF Report Viewer"
            />
          ) : (
            <div className="flex flex-col items-center justify-center p-20 bg-white rounded-2xl w-full max-w-2xl mt-12 h-64 border border-slate-200">
              <AlertTriangle className="w-12 h-12 text-orange-500 mb-4" />
              <p className="font-bold text-slate-800 text-lg">Aucun PDF n'a été généré pour cette analyse.</p>
              <p className="text-slate-500 text-sm mt-2">Le moteur backend n'a pas pu créer le fichier.</p>
            </div>
          )}
        </div>
      )}

      {viewMode === 'archives' && (
        <div className="flex-1 w-full bg-slate-50 p-8 overflow-y-auto">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-2xl font-black text-[#04243C] uppercase tracking-tight mb-6 flex items-center">
              <Database className="w-6 h-6 mr-3 text-orange-500" />
              Historique des Analyses PDF
            </h2>
            
            {archivesList.length > 0 ? (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {archivesList.map((file, idx) => (
                  <div key={idx} className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm hover:shadow-md transition-all flex justify-between items-center group">
                    <div>
                      <h4 className="font-bold text-slate-800 text-sm mb-1 line-clamp-1">{file.name}</h4>
                      <p className="text-xs text-slate-500">{new Date(file.date).toLocaleString('fr-FR')}</p>
                    </div>
                    <div className="flex gap-2">
                       <button onClick={() => { setSelectedArchiveUrl(file.url); setViewMode('full'); }} className="p-2 bg-slate-50 hover:bg-slate-100 text-[#04243C] rounded-lg transition-colors border border-slate-200" title="Lire">
                          <Eye className="w-4 h-4" />
                       </button>
                       <a href={file.url} download className="p-2 bg-orange-50 hover:bg-orange-100 text-orange-600 rounded-lg transition-colors border border-orange-200" title="Télécharger">
                          <Download className="w-4 h-4" />
                       </a>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="text-center p-16 bg-white border border-slate-200 rounded-2xl">
                <FileText className="w-12 h-12 text-slate-300 mx-auto mb-4" />
                <p className="text-slate-500 font-medium">Aucun rapport PDF n'a été sauvegardé dans l'historique.</p>
              </div>
            )}
          </div>
        </div>
      )}

    </div>
  );
}
